# Generated by Django 3.1.3 on 2021-01-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=models.ImageField(default='', upload_to='store/static'),
        ),
    ]
