# Generated by Django 3.1.3 on 2021-01-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_name_for_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name_for_search',
            new_name='search_for_name',
        ),
    ]
