# Generated by Django 3.1.3 on 2021-01-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20210123_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='save',
        ),
        migrations.AddField(
            model_name='product',
            name='save1',
            field=models.IntegerField(default=0),
        ),
    ]
