# Generated by Django 3.1.3 on 2021-01-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210123_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='save1',
            new_name='saving',
        ),
    ]
