# Generated by Django 3.1.3 on 2023-06-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_auto_20230615_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='modalities',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
