# Generated by Django 3.1.3 on 2023-06-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_users_modalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='services',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
