# Generated by Django 3.1.3 on 2023-06-25 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20230624_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='slots',
        ),
    ]
