# Generated by Django 3.1.3 on 2023-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_users_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='audiometry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='ecg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='eye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='pft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='vitals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='xray',
            field=models.BooleanField(default=False),
        ),
    ]
