# Generated by Django 3.1.3 on 2023-07-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20230704_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='weight',
            field=models.FloatField(default=None, null=True),
        ),
    ]
