# Generated by Django 3.1.3 on 2023-07-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20230705_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='audiometry',
        ),
        migrations.RemoveField(
            model_name='users',
            name='ecg',
        ),
        migrations.RemoveField(
            model_name='users',
            name='eye',
        ),
        migrations.RemoveField(
            model_name='users',
            name='pft',
        ),
        migrations.RemoveField(
            model_name='users',
            name='vitals',
        ),
        migrations.RemoveField(
            model_name='users',
            name='xray',
        ),
    ]
