# Generated by Django 3.1.3 on 2023-07-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20230705_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray', models.BooleanField(default=False)),
                ('ecg', models.BooleanField(default=False)),
                ('pft', models.BooleanField(default=False)),
                ('audiometry', models.BooleanField(default=False)),
                ('eye', models.BooleanField(default=False)),
                ('vitals', models.BooleanField(default=False)),
            ],
        ),
    ]
