# Generated by Django 3.1.3 on 2023-07-06 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(max_length=20, null=True)),
                ('xray', models.BooleanField(default=False)),
                ('ecg', models.BooleanField(default=False)),
                ('pft', models.BooleanField(default=False)),
                ('audiometry', models.BooleanField(default=False)),
                ('eye', models.BooleanField(default=False)),
                ('vitals', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Modality',
        ),
        migrations.AddField(
            model_name='users',
            name='patientID',
            field=models.IntegerField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='modalities',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.users'),
        ),
    ]
