# Generated by Django 3.1.3 on 2023-10-12 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_coordinator_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalities',
            name='customer',
        ),
        migrations.AlterField(
            model_name='modalities',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='patientID',
            field=models.IntegerField(default=None),
        ),
    ]
