# Generated by Django 3.1.3 on 2023-10-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20231012_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='patientID',
            field=models.IntegerField(),
        ),
    ]
