# Generated by Django 3.1.3 on 2023-10-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20231012_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='patientID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
