# Generated by Django 3.1.3 on 2023-10-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20231012_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalities',
            name='optometry',
            field=models.BooleanField(default=False),
        ),
    ]
