# Generated by Django 3.1.3 on 2023-10-16 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_auto_20231014_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalities',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='modalities',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.users'),
        ),
    ]
