# Generated by Django 3.1.3 on 2023-10-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_auto_20231016_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
