# Generated by Django 3.1.3 on 2023-10-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20231016_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='patient_id',
        ),
    ]
