# Generated by Django 3.1.3 on 2023-10-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_remove_modalities_eye'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalities',
            name='sample_collection',
            field=models.BooleanField(default=False),
        ),
    ]
