# Generated by Django 3.1.3 on 2023-10-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_modalities_sample_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='patient_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
