# Generated by Django 3.1.3 on 2023-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_users_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalities',
            name='patient',
        ),
        migrations.AddField(
            model_name='modalities',
            name='patient',
            field=models.ManyToManyField(blank=True, to='store.Users'),
        ),
    ]
