# Generated by Django 3.1.3 on 2023-11-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_auto_20231101_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalities',
            name='patient',
        ),
        migrations.AddField(
            model_name='modalities',
            name='patient',
            field=models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='store.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='patient_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
