# Generated by Django 3.1.3 on 2023-11-04 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_auto_20231104_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalities',
            name='patient',
        ),
        migrations.AddField(
            model_name='modalities',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.users'),
        ),
    ]
