# Generated by Django 3.1.3 on 2023-11-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_auto_20231104_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modalities',
            old_name='customer',
            new_name='patient',
        ),
    ]
