# Generated by Django 3.1.3 on 2023-11-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_auto_20231104_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalities',
            name='patient',
        ),
        migrations.AddField(
            model_name='modalities',
            name='patient',
            field=models.ManyToManyField(to='store.Users'),
        ),
    ]
