# Generated by Django 3.1.3 on 2023-11-04 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0057_auto_20231104_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalities',
            name='patient',
        ),
        migrations.AddField(
            model_name='modalities',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.users'),
        ),
    ]
