# Generated by Django 3.1.3 on 2023-11-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0058_auto_20231104_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modalities',
            name='patient',
        ),
    ]
