# Generated by Django 3.1.3 on 2023-11-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_modalities_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalities',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.users'),
        ),
    ]
