# Generated by Django 3.1.3 on 2023-11-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_auto_20231104_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='audiometry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='ecg',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='optometry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='pft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='sample_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='vitals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='xray',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Modalities',
        ),
    ]
