# Generated by Django 3.1.3 on 2023-11-18 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_auto_20231106_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('far_vision_right', models.CharField(max_length=10)),
                ('far_vision_left', models.CharField(max_length=10)),
                ('near_vision_right', models.CharField(max_length=10)),
                ('near_vision_left', models.CharField(max_length=10)),
                ('others', models.CharField(max_length=300)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optometry_results', to='store.users')),
            ],
        ),
    ]
