# Generated by Django 3.1.3 on 2023-11-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0063_optometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='optometry',
            name='color_vision',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('RED', 'Red'), ('GREEN', 'Green'), ('RED_GREEN', 'Red-green'), ('DEFICIENCY', 'deficiency')], default=True, max_length=15),
        ),
    ]
