# Generated by Django 3.1.3 on 2023-11-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_optometry_color_vision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
