# Generated by Django 3.1.3 on 2023-11-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_auto_20231122_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_field',
            field=models.DateField(default=None),
        ),
    ]
