# Generated by Django 3.1.3 on 2023-11-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_users_date_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='location',
        ),
    ]
