# Generated by Django 3.1.3 on 2023-11-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0068_auto_20231122_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.location'),
        ),
    ]
