# Generated by Django 3.1.3 on 2023-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0070_auto_20231125_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sample_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='vitals',
            field=models.BooleanField(default=False),
        ),
    ]
