# Generated by Django 3.1.3 on 2023-11-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0071_auto_20231125_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='technician_name',
            field=models.CharField(default='Unknown Technician', max_length=100),
        ),
    ]
