# Generated by Django 3.1.3 on 2023-12-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_auto_20231205_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='currect_time',
            new_name='current_time',
        ),
    ]
