# Generated by Django 5.0.1 on 2024-02-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0076_auto_20231205_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_field',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
