# Generated by Django 5.0.1 on 2024-02-05 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0078_alter_users_date_field_alter_users_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='store.location'),
        ),
    ]
